version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: >-
    Install-Product node $env:nodejs_version
      node --version && npm --version
      git --version && svn --version
      npm install
before_build:
- cmd: >-
    bower install

    dotnet --version

    dotnet restore --verbosity m
build:
  project: Chronos.sln
  verbosity: minimal
test_script:
- cmd: dotnet test Chronos.Tests\Chronos.Tests.csproj