version: 1.0.{build}
image: Visual Studio 2017

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "6"

# Finish on first failed build
matrix:
  fast_finish: true

# Install node, display versions, install dependencies
install:
  #- ps: Install-Product node $env:nodejs_version
  #- node --version && npm --version
  #- git --version && svn --version
  - npm install -g bower
before_build:
  - cmd: pushd Chronos.Web && bower install && popd
    #- cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build:
  project: Chronos.sln
  verbosity: minimal
test_script:
  - cmd: dotnet test Chronos.Tests\Chronos.Tests.csproj
on_failure:
  - cmd: 7z a SqlTests.zip Chronos.Tests\bin\Debug\netcoreapp2.0\*.dll
  - cmd: appveyor PushArtifact SqlTests.zip
  # Cache node modules, and refresh if package.json changes
cache:
  - node_modules -> package.json
artifacts:
  - path: SqlTests.zip
    name: SqlTests
