// <auto-generated />
using Chronos.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Chronos.Persistence.Migrations.Read
{
    [DbContext(typeof(ReadContext))]
    [Migration("20170909081610_CoinStats")]
    partial class CoinStats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Chronos.Core.Accounts.Projections.AccountInfo", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Balance");

                    b.Property<DateTime>("CreatedAtUtc");

                    b.Property<string>("Currency");

                    b.Property<string>("Name");

                    b.HasKey("Key");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Chronos.Core.Accounts.Projections.TotalMovement", b =>
                {
                    b.Property<Guid>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Value");

                    b.HasKey("Key");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("Chronos.Core.Projections.Stats", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumberOfAccounts");

                    b.Property<int>("NumberOfAssets");

                    b.HasKey("Key");

                    b.ToTable("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
